(function () {
  const TOKEN_KEY = "firstseries-user-token";

  let currentUser = null;
  let modeInscription = false;
  let syncTimer = null;
  let syncQueue = Promise.resolve();
  function token(){ return localStorage.getItem(TOKEN_KEY) || ""; }
  function headers(){ return {"Content-Type":"application/json", ...(token()?{Authorization:`Bearer ${token()}`}:{})}; }
  async function api(url, options={}) { const r=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.erreur||"Erreur serveur"); return d; }
  function injecter(){
    document.querySelectorAll('.site-header').forEach(header=>{
      let zone=header.querySelector('#header-auth-zone,.header-right'); if(!zone){zone=document.createElement('div');zone.className='header-right';header.appendChild(zone);}
      if(!zone.querySelector('[data-auth-open]')&&!zone.querySelector('[data-user-menu]')) zone.insertAdjacentHTML('beforeend',`<button type="button" class="auth-open-btn" data-auth-open>Se connecter / S'inscrire</button><div class="user-menu" data-user-menu hidden><button type="button" class="user-menu-button" data-user-menu-button><span class="user-avatar" data-user-avatar>?</span><span class="user-name" data-user-name></span></button><div class="user-menu-panel" data-user-menu-panel hidden><div class="user-menu-email" data-user-menu-email></div><button type="button" data-logout-button>Se déconnecter</button></div></div>`);
    });
  }
  function modal(){ if(document.getElementById('auth-modal-overlay'))return; const o=document.createElement('div');o.id='auth-modal-overlay';o.className='auth-modal-overlay';o.hidden=true;o.innerHTML=`<div class="auth-modal"><div class="auth-card"><button type="button" class="auth-modal-close" id="auth-modal-close">✕</button><div class="auth-card-head"><span class="auth-kicker">Compte</span><h2 id="auth-modal-title">Connexion</h2><p id="auth-modal-subtitle">Connecte-toi pour retrouver ta lecture sur tous tes appareils.</p></div><form class="auth-form" id="auth-form"><label>Email</label><input type="email" id="auth-email" required autocomplete="email"><label>Mot de passe</label><input type="password" id="auth-password" required minlength="6" autocomplete="current-password"><button type="submit" class="auth-submit" id="auth-submit-btn">Se connecter</button><p class="auth-error" id="auth-modal-error"></p></form><p class="auth-switch"><span id="auth-switch-text">Pas encore de compte ?</span><button type="button" class="text-button" id="auth-switch-btn">Créer un compte</button></p></div></div>`;document.body.appendChild(o);}
  function ui(){document.querySelectorAll('[data-auth-open]').forEach(x=>x.hidden=!!currentUser);document.querySelectorAll('[data-user-menu]').forEach(x=>x.hidden=!currentUser);if(currentUser){const n=(currentUser.email||'').split('@')[0],i=(n[0]||'?').toUpperCase();document.querySelectorAll('[data-user-avatar]').forEach(x=>x.textContent=i);document.querySelectorAll('[data-user-name]').forEach(x=>x.textContent=n);document.querySelectorAll('[data-user-menu-email]').forEach(x=>x.textContent=currentUser.email);}}
  function setMode(){document.getElementById('auth-modal-title').textContent=modeInscription?'Créer un compte':'Connexion';document.getElementById('auth-submit-btn').textContent=modeInscription?'Créer mon compte':'Se connecter';document.getElementById('auth-switch-text').textContent=modeInscription?'Déjà un compte ?':'Pas encore de compte ?';document.getElementById('auth-switch-btn').textContent=modeInscription?'Se connecter':'Créer un compte';}
  async function chargerProgression(){if(!currentUser)return;try{const d=await api('/api/progress');const locales=window.lireLecturesEnCours?window.lireLecturesEnCours():[];const map=new Map();[...(d.lectures||[]),...locales].forEach(x=>{if(!x)return;const k=[x.serieId,x.saisonId,x.episodeId,x.type].join('|');if(!map.has(k)||(x.timestamp||0)>(map.get(k).timestamp||0))map.set(k,x);});const fusion=[...map.values()].sort((a,b)=>(b.timestamp||0)-(a.timestamp||0)).slice(0,12);if(window.sauvegarderLecturesEnCours)window.sauvegarderLecturesEnCours(fusion,{skipCloud:true});await pousser(fusion);if(window.rafraichirEnCoursLecture)window.rafraichirEnCoursLecture();}catch(e){console.warn('Progression SQL:',e.message);}}
  function pousser(lectures){if(!currentUser)return Promise.resolve();syncQueue=syncQueue.then(()=>api('/api/progress',{method:'PUT',body:JSON.stringify({lectures:(lectures||[]).slice(0,12)})})).catch(e=>console.warn('Sauvegarde progression:',e.message));return syncQueue;}
  window.__pousserLecturesVersCloud=pousser;
  async function submit(e){e.preventDefault();const email=document.getElementById('auth-email').value.trim(),motDePasse=document.getElementById('auth-password').value,btn=document.getElementById('auth-submit-btn');btn.disabled=true;try{const d=await api(modeInscription?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify({email,motDePasse})});localStorage.setItem(TOKEN_KEY,d.token);currentUser=d.user;document.getElementById('auth-modal-overlay').hidden=true;document.getElementById('auth-form').reset();ui();await chargerProgression();}catch(e){document.getElementById('auth-modal-error').textContent=e.message;}finally{btn.disabled=false;}}
  async function init(){injecter();modal();document.addEventListener('click',async e=>{if(e.target.closest('[data-auth-open]'))document.getElementById('auth-modal-overlay').hidden=false;else if(e.target.id==='auth-modal-close'||e.target.id==='auth-modal-overlay')document.getElementById('auth-modal-overlay').hidden=true;else if(e.target.id==='auth-switch-btn'){modeInscription=!modeInscription;setMode();}else if(e.target.closest('[data-logout-button]')){localStorage.removeItem(TOKEN_KEY);currentUser=null;ui();}else if(e.target.closest('[data-user-menu-button]')){const p=e.target.closest('[data-user-menu]').querySelector('[data-user-menu-panel]');p.hidden=!p.hidden;}});document.getElementById('auth-form').addEventListener('submit',submit);if(token()){try{const d=await api('/api/auth/me');currentUser=d.user;ui();await chargerProgression();}catch(e){localStorage.removeItem(TOKEN_KEY);currentUser=null;ui();}}}
  document.addEventListener('DOMContentLoaded',init);
})();
